const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND_CODE = 404;
const CONFLICT = 409;
const INTERNAL_SERVER_ERROR_CODE = 500;

module.exports = {
  BAD_REQUEST_CODE,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND_CODE,
  CONFLICT,
  INTERNAL_SERVER_ERROR_CODE,
};
